"""Emit the reproducible build artifacts: JSON manifest + PRODUCTS_SEED-compatible module.

The emitted ``generated_products.py`` exposes one plain-data structure that the
existing ``seed_catalog_dummy`` seeder ingests via an additive merge:

* ``GENERATED_PRODUCTS_SEED`` — list of dicts in the exact ``PRODUCTS_SEED`` shape.
"""
from __future__ import annotations

import json
import pprint
from pathlib import Path
from typing import List


_MODULE_HEADER = '''\
"""AUTO-GENERATED by app.catalog_gen — do not edit by hand.

Reproducible synthetic catalog dataset (PRODUCTS_SEED-compatible). Regenerate with::

    python -m app.catalog_gen --count {count} --seed {seed}

Every record here was verified by the ΔE2000 QA gate before being emitted.
"""
'''


def _py_literal(obj) -> str:
    return pprint.pformat(obj, sort_dicts=False, width=100)


def ensure_seed_package(seed_out: Path) -> None:
    """Make sure the emitted module is importable as a package."""
    pkg = seed_out.parent
    pkg.mkdir(parents=True, exist_ok=True)
    init = pkg / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Generated seed data (auto-produced by app.catalog_gen)."""\n', encoding="utf-8"
        )


def write_seed_module(
    seed_out: Path,
    products: List[dict],
    *,
    count: int,
    seed: int,
) -> None:
    ensure_seed_package(seed_out)
    parts = [
        _MODULE_HEADER.format(count=count, seed=seed),
        "",
        "GENERATED_PRODUCTS_SEED = " + _py_literal(products),
        "",
    ]
    seed_out.write_text("\n".join(parts), encoding="utf-8")


def write_manifest(manifest_path: Path, payload: dict) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
