"""Emit the reproducible build artifacts: JSON manifest + PRODUCTS_SEED-compatible module.

The emitted ``generated_products.py`` exposes three plain-data structures that the
**unchanged** existing seeders ingest via additive merges:

* ``GENERATED_PRODUCTS_SEED``   — list of dicts in the exact ``PRODUCTS_SEED`` shape.
* ``GENERATED_FACE_ANCHORS``    — ``image_url -> anchor_config`` (merged into FACE_ANCHORS).
* ``GENERATED_VTON_ASSET_SEED`` — ``image_url -> vton spec`` (merged into VTON_ASSET_SEED).

Tier values are written as plain strings (identical to the ``TIER_*`` constants), so the
file is import-cheap and the existing tier→status/quality mappings key on them unchanged.
"""
from __future__ import annotations

import json
import pprint
from pathlib import Path
from typing import List


_MODULE_HEADER = '''\
"""AUTO-GENERATED by app.catalog_gen — do not edit by hand.

Reproducible synthetic catalog dataset (PRODUCTS_SEED-compatible) plus the
template-inherited face-anchor and VTON-asset lookups. Regenerate with::

    python -m app.catalog_gen --count {count} --seed {seed}

Every record here was verified by the ΔE2000 QA gate before being emitted.
"""
'''


def _py_literal(obj) -> str:
    return pprint.pformat(obj, sort_dicts=False, width=100)


def ensure_seed_package(seed_out: Path) -> None:
    """Make sure the emitted module is importable as a package."""
    pkg = seed_out.parent
    pkg.mkdir(parents=True, exist_ok=True)
    init = pkg / "__init__.py"
    if not init.exists():
        init.write_text('"""Generated seed data (auto-produced by app.catalog_gen)."""\n')


def write_seed_module(
    seed_out: Path,
    products: List[dict],
    anchors: dict,
    vton: dict,
    *,
    count: int,
    seed: int,
) -> None:
    ensure_seed_package(seed_out)
    parts = [
        _MODULE_HEADER.format(count=count, seed=seed),
        "",
        "GENERATED_PRODUCTS_SEED = " + _py_literal(products),
        "",
        "GENERATED_FACE_ANCHORS = " + _py_literal(anchors),
        "",
        "GENERATED_VTON_ASSET_SEED = " + _py_literal(vton),
        "",
    ]
    seed_out.write_text("\n".join(parts))


def write_manifest(manifest_path: Path, payload: dict) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(payload, indent=2, sort_keys=True))
